export const generalSettingsData = [
  'site_name',
  'site_url',
  'site_email',
  'default_country',
  'default_currency',
  'registration_status',
  'free_usage_word_upon_registration',
  'free_usage_image_upon_registration',
  'social_login_facebook_status',
  'social_login_google_status',
  'google_analytics_tracking_id',
  'meta_title',
  'meta_description',
  'meta_keywords',
  'site_logo',
  'site_fav_icon',
];
