export const coreConstant = {
  USER_ROLE_ADMIN: 1,
  USER_ROLE_USER: 2,
  COMMON_PASSWORD: '123456',
  STATUS_INACTIVE: 0,
  STATUS_ACTIVE: 1,
  STATUS_PENDING: 2,
  IS_VERIFIED: 1,
  IS_NOT_VERIFIED: 0,
  VERIFICATION_TYPE_EMAIL: 1,
  FILE_DESTINATION: 'uploads',
  ACTIVE: 1,
  INACTIVE: 0,
  PENDING: 2,
  PACKAGE_TYPES: {
    SUBSCRIPTION: 1,
    PACKAGE: 2,
  },
  PAYMENT_METHODS: {
    STRIPE: 1,
    PAYPAL: 2,
  },
  PACKAGE_DURATION: {
    WEEKLY: 1,
    MONTHLY: 2,
    YEARLY: 3,
  },
};
